apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chart.fullname" . }}-initializers
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  initializerJson.json: |
{{ .Files.Get "static/initializerJson.json" | printf "%s" | indent 4 }}
